In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.model_selection import RandomizedSearchCV

In [3]:
df = pd.read_csv('../data/processed/processed_data.csv')

In [4]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Paperless Billing,Monthly Charges,Total Charges,Churn Label,CLTV,...,Device Protection_Yes,Tech Support_Yes,Streaming TV_Yes,Streaming Movies_Yes,Contract_One year,Contract_Two year,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check,HighCharge_MonthlyContract
0,1,0,0,0,2,1,53.85,108.15,1,3239,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,1,2,1,70.70,151.65,1,2701,...,0,0,0,0,0,0,0,1,0,1
2,0,0,0,1,8,1,99.65,820.50,1,5372,...,1,0,1,1,0,0,0,1,0,1
3,0,0,1,1,28,1,104.80,3046.05,1,5003,...,1,1,1,1,0,0,0,1,0,1
4,1,0,0,1,49,1,103.70,5036.30,1,5340,...,1,0,1,1,0,0,0,0,0,1

In [5]:
X = df.drop("Churn Label", axis=1)
y = df["Churn Label"]

In [6]:
X_test, X_train, y_test, y_train = train_test_split(X, y, test_size=0.2, random_state=42 ,stratify=y)

In [7]:
scaler = StandardScaler()

scale_cols = [
    'Tenure Months',
    'Monthly Charges',
    'Total Charges',
    'CLTV'
]

X_train_scaled = X_train.copy()
X_test_scaled=  X_test.copy()

X_train_scaled[scale_cols] = scaler.fit_transform(X_train[scale_cols])
X_test_scaled[scale_cols] = scaler.transform(X_test[scale_cols])

In [8]:
lr = LogisticRegression(
    random_state = 42,
    max_iter = 1000
)
lr.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [9]:
y_pred = lr.predict(X_test_scaled)
y_pred

array([0, 0, 0, ..., 0, 0, 1], shape=(5625,))

In [10]:
y_prob = lr.predict_proba(X_test_scaled)[:, 1]
y_prob

array([0.00819268, 0.12395297, 0.02462355, ..., 0.02932232, 0.19308841,
       0.79554773], shape=(5625,))

In [11]:
def evaluate_model(model, X_test, y_test):
    
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:,1]

    print("Accuracy :", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall   :", recall_score(y_test, y_pred))
    print("F1 Score :", f1_score(y_test, y_pred))
    print("ROC AUC  :", roc_auc_score(y_test, y_prob))

    print("\nClassification Report\n")
    print(classification_report(y_test, y_pred))

In [12]:
evaluate_model(lr , X_test_scaled, y_test)
evaluate_model

Accuracy : 0.8076444444444445
Precision: 0.6728033472803348
Recall   : 0.5377926421404682
F1 Score : 0.5977695167286246
ROC AUC  : 0.853404164001069

Classification Report

              precision    recall  f1-score   support

           0       0.84      0.91      0.87      4130
           1       0.67      0.54      0.60      1495

    accuracy                           0.81      5625
   macro avg       0.76      0.72      0.74      5625
weighted avg       0.80      0.81      0.80      5625

In [13]:
dt = DecisionTreeClassifier(
    random_state=42,
    max_depth = 5
)

dt.fit(X_train_scaled, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [14]:
import joblib

joblib.dump(lr, "../models/logistic_regression.pkl")
joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']

In [15]:
evaluate_model(dt, X_test, y_test)

Accuracy : 0.7660444444444444
Precision: 0.5680608365019011
Recall   : 0.49966555183946487
F1 Score : 0.5316725978647687
ROC AUC  : 0.7147366119510555

Classification Report

              precision    recall  f1-score   support

           0       0.83      0.86      0.84      4130
           1       0.57      0.50      0.53      1495

    accuracy                           0.77      5625
   macro avg       0.70      0.68      0.69      5625
weighted avg       0.76      0.77      0.76      5625

In [16]:
rf = RandomForestClassifier(random_state=42)
param_dist = {
    "n_estimators": [100, 200, 300, 500],
    "max_depth": [5, 10, 15, 20, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2"],
    "class_weight": [None, "balanced"]
}
rf_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=30,
    scoring="f1",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=2
)

rf_search.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'class_weight': [None, 'balanced'],
                                        'max_depth': [5, 10, 15, 20, None],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 500]},
                   random_state=42, scoring='f1', verbose=2)

In [17]:
best_rf = rf_search.best_estimator_
evaluate_model(best_rf, X_test, y_test)

Accuracy : 0.7790222222222222
Precision: 0.565625
Recall   : 0.7264214046822742
F1 Score : 0.6360175695461201
ROC AUC  : 0.8477297205373844

Classification Report

              precision    recall  f1-score   support

           0       0.89      0.80      0.84      4130
           1       0.57      0.73      0.64      1495

    accuracy                           0.78      5625
   macro avg       0.73      0.76      0.74      5625
weighted avg       0.80      0.78      0.79      5625

In [18]:
evaluate_model(rf_search.best_estimator_, X_test, y_test)

Accuracy : 0.7790222222222222
Precision: 0.565625
Recall   : 0.7264214046822742
F1 Score : 0.6360175695461201
ROC AUC  : 0.8477297205373844

Classification Report

              precision    recall  f1-score   support

           0       0.89      0.80      0.84      4130
           1       0.57      0.73      0.64      1495

    accuracy                           0.78      5625
   macro avg       0.73      0.76      0.74      5625
weighted avg       0.80      0.78      0.79      5625

In [19]:
import joblib

joblib.dump(rf, "../models/random_forest.pkl")

['../models/random_forest.pkl']

In [20]:
joblib.dump(dt, "../models/decision_tree.pkl")

['../models/decision_tree.pkl']

In [19]:
scale_pos_weight = (
    len(y_train[y_train == 0]) / len(y_train[y_train == 1])
)
scale_pos_weight

2.7620320855614975

In [20]:
xgb = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

param_dist = {

    "n_estimators":[100,200,300,500],
    "learning_rate":[0.01,0.03,0.05,0.1],
    "max_depth":[3,4,5,6,8],
    "min_child_weight":[1,3,5,7],
    "gamma":[0,0.1,0.3,0.5],

    "subsample":[0.6,0.8,1.0],

    "colsample_bytree":[0.6,0.8,1.0],

    "reg_alpha":[0,0.1,0.5,1],

    "reg_lambda":[1,2,5],

    "scale_pos_weight":[scale_pos_weight]
}
xgb_search = RandomizedSearchCV(

    estimator=xgb,

    param_distributions=param_dist,

    n_iter=30,

    scoring="f1",

    cv=5,

    random_state=42,

    n_jobs=-1,

    verbose=2

)

xgb_search.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=True,
                                           eval_metric='logloss',
                                           feature_types=None,
                                           feature_weights=None, gamma=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_const...
                   param_distributions={'colsample_bytree': [0.6, 0.8, 1.0],
                                        'gamma': [0, 0.1, 0.3, 0.5],
                                        'learning_rate': [0.01, 0.03, 0.05,
                                                          0.1],
                                        'max_depth': [3, 4, 5, 6, 8],
                                        'min_child_weight': [1, 3, 5, 7],
                                        'n_estimators': [100, 200, 300, 500],
                                        'reg_alpha': [0, 0.1, 0.5, 1],
                                        'reg_lambda': [1, 2, 5],
                                        'scale_pos_weight': [2.7620320855614975],
                                        'subsample': [0.6, 0.8, 1.0]},
                   random_state=42, scoring='f1', verbose=2)

In [21]:
best_xgb = xgb_search.best_estimator_

evaluate_model(best_xgb, X_test, y_test)

Accuracy : 0.7770666666666667
Precision: 0.5598014888337469
Recall   : 0.7545150501672241
F1 Score : 0.6427350427350428
ROC AUC  : 0.8506556155708698

Classification Report

              precision    recall  f1-score   support

           0       0.90      0.79      0.84      4130
           1       0.56      0.75      0.64      1495

    accuracy                           0.78      5625
   macro avg       0.73      0.77      0.74      5625
weighted avg       0.81      0.78      0.79      5625

In [ ]:
scale_pos_weight = len(y_train[y_train == 0]) / len(y_train[y_train == 1])

print(scale_pos_weight)

2.7620320855614975

In [23]:
from lightgbm import LGBMClassifier

lgbm = LGBMClassifier(random_state=42)

param_dist = {

    "n_estimators":[100,200,300,500],

    "learning_rate":[0.01,0.03,0.05,0.1],

    "max_depth":[3,5,7,-1],

    "num_leaves":[15,31,50,70],

    "min_child_samples":[10,20,30],

    "subsample":[0.6,0.8,1.0],

    "colsample_bytree":[0.6,0.8,1.0],

    "reg_alpha":[0,0.1,0.5],

    "reg_lambda":[0,1,5],

    "class_weight":[None,"balanced"]
}
lgbm_search = RandomizedSearchCV(

    estimator=lgbm,

    param_distributions=param_dist,

    n_iter=30,

    scoring="f1",

    cv=5,

    random_state=42,

    n_jobs=-1,

    verbose=2

)

lgbm_search.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 374, number of negative: 1033
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000237 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 878
[LightGBM] [Info] Number of data points in the train set: 1407, number of used features: 24
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

RandomizedSearchCV(cv=5, estimator=LGBMClassifier(random_state=42), n_iter=30,
                   n_jobs=-1,
                   param_distributions={'class_weight': [None, 'balanced'],
                                        'colsample_bytree': [0.6, 0.8, 1.0],
                                        'learning_rate': [0.01, 0.03, 0.05,
                                                          0.1],
                                        'max_depth': [3, 5, 7, -1],
                                        'min_child_samples': [10, 20, 30],
                                        'n_estimators': [100, 200, 300, 500],
                                        'num_leaves': [15, 31, 50, 70],
                                        'reg_alpha': [0, 0.1, 0.5],
                                        'reg_lambda': [0, 1, 5],
                                        'subsample': [0.6, 0.8, 1.0]},
                   random_state=42, scoring='f1', verbose=2)

In [ ]:
evaluate_model(lgbm_search.best_estimator_, X_test, y_test)

Accuracy : 0.7646222222222222
Precision: 0.5393103448275862
Recall   : 0.7846153846153846
F1 Score : 0.6392370572207084
ROC AUC  : 0.8519487071513601

Classification Report

              precision    recall  f1-score   support

           0       0.91      0.76      0.83      4130
           1       0.54      0.78      0.64      1495

    accuracy                           0.76      5625
   macro avg       0.72      0.77      0.73      5625
weighted avg       0.81      0.76      0.78      5625

In [ ]:
best_model = xgb_search.best_estimator_
joblib.dump(best_model, "../models/xgboost_best.pkl")
print("Done")

Done

In [ ]:
lightbgm = lgbm_search.best_estimator_
joblib.dump(lightbgm, "../models/lightgbm_best.pkl")
print("Done")

Done

In [ ]:
feature_names = X.columns.tolist()
joblib.dump(feature_names, "../models/feature_names.pkl")

['../models/feature_names.pkl']

In [25]:
comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost",
        "LightGBM"
    ],
    "Accuracy": [
        0.8076,
        0.7660,
        0.7790,
        0.7771,
        0.7646
    ],
    "Precision": [
        0.6728,
        0.5681,
        0.5656,
        0.5598,
        0.5393
    ],
    "Recall": [
        0.5378,
        0.5000,
        0.7264,
        0.7545,
        0.7846
    ],
    "F1 Score": [
        0.5978,
        0.5317,
        0.6360,
        0.6427,
        0.6392
    ],
    "ROC AUC": [
        0.8534,
        0.7147,
        0.8477,
        0.8507,
        0.8519
    ]
})

comparison.to_csv("../results/model_comparison.csv", index=False)
comparison

                 Model  Accuracy  Precision  Recall  F1 Score  ROC AUC
0  Logistic Regression    0.8076     0.6728  0.5378    0.5978   0.8534
1        Decision Tree    0.7660     0.5681  0.5000    0.5317   0.7147
2        Random Forest    0.7790     0.5656  0.7264    0.6360   0.8477
3              XGBoost    0.7771     0.5598  0.7545    0.6427   0.8507
4             LightGBM    0.7646     0.5393  0.7846    0.6392   0.8519

In [29]:
y_test.to_csv("../results/y_test.csv", index=False)

pd.Series(y_pred).to_csv("../results/y_pred.csv", index=False)

pd.Series(y_prob).to_csv("../results/y_prob.csv", index=False)